# Generated by Django 2.2.4 on 2019-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0002_auto_20190829_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Done')], default=1, max_length=1),
        ),
    ]
